.TH hello-packaging 1 "17 July 2025" "" ""
.SH NAME
\fBhello-packaging \fP- Demo Debian package
\fB
.SH SYNOPSIS
.nf
.fam C

\fBhello-packaging\fP [\fIoptions\fP]

.fam T
.fi
.fam T
.fi
.SH DESCRIPTION

\fBhello-packaging\fP serves as a quick demo for how to debianize software. The
actual binary is a single shell script that echoes a 'hello' message.
.SH EXAMPLES

To print the message
.SH I/O:

\fBlandscape-client\fP

.SH AUTHOR
Your Fullname <youremail@example.com>
